/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:50d280c9-353e-429f-8b90-7a7222b8d6c1",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_WPcWqsPK8",
    "aws_user_pools_web_client_id": "2lu6b734p7e1d89uja66crqock",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://kvp5oatvf5dpdd4ags6xowib4e.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-z62gddv7cfatfdljzhbzzwfxsu",
    "aws_user_files_s3_bucket": "amplifyapp663f0f40d9d64513ade6e54081caa054220339-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
