/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:50d280c9-353e-429f-8b90-7a7222b8d6c1",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_WPcWqsPK8",
    "aws_user_pools_web_client_id": "2lu6b734p7e1d89uja66crqock",
    "oauth": {}
};


export default awsmobile;
